export const AUTH_START = 'AUTH/AUTH_START';
export const AUTH_SUCCESS = 'AUTH/AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH/AUTH_FAIL';
export const AUTH_REGISTRATION_SUCCESS = 'AUTH/AUTH_REGISTRATION_SUCCESS'
